### ISSUE TITLE
[Feature request] Tooltips styling

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-config#1030]
Some elements aren't styled according to palette colors, like tooltips in pcmanfm-qt.

**Comment by tsujan** [comment]
Tooltips aren't touched anywhere because their colors aren't added to the palette (yet).

The styled tooltips you may see exist only in those components that are styled by LXQt Style, which uses Qt's style-sheet engine. There are are only a few of them: most importantly, Panel, Runner, and notifications. All other Qt apps are styled by the active Qt style (Fusion, Breeze, Kvantum,...).

**Comment by isf63** [comment]
> styled by LXQt Style [...] Panel, Runner, and notifications

Is Configuration Center the only other one?

**Comment by tsujan** [comment]
> Is Configuration Center the only other one?

Maybe. But it's better to use style-sheets with it only for its icon size and, perhaps, tooltips. Anything else can easily become problematic because of the clash between style-sheet and Qt style.

**Comment by tsujan** [comment]
The new GUI will be like this:

![tooltips](https://github.com/user-attachments/assets/233cce48-65e1-4313-a0c8-11ff02c9a82c)

I tested it and saw no problem.
