### ISSUE TITLE
[lxqt-config] Add HiDPI configuration

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/lxqt-config#402]
Carrying over from #916, we need a menu for HiDPI configuration.

**Comment by tsujan** [comment]
> We should really work on this - not only talk.

A little more talk and I'll shut my mouth: LXQt has a nice GUI for settings EVs. There are 2 HDPI variables, one for Qt and the other for GTK+. Not-so-advanced users are aware of them and could set them. So, LXQt has no practical problem with HDPI.

A separate GUI may be good for newbies; nothing more.

And please don't mistake HDPI setting with font/icon size setting!

**Comment by shlyakpavel** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19782228/63799940-c817a600-c915-11e9-8b68-27d189e7fdfd.png">

That's the default LXQt on my 13 inch 261ppi screen :(

**Comment by agaida** [comment]
imagine you had a really high resolution screen :D

**Comment by tsujan** [comment]
@shlyakpavel Qt has something called "scale factor". Consult Qt doc.

**Comment by tsujan** [comment]
Example:

![scale_factor](https://user-images.githubusercontent.com/981076/63805798-74b25180-c92f-11e9-8bd5-a7d243f31a82.png)

**Comment by renom** [comment]
It'd be great to be able to change DPI settings without restarting everything. It can already be done for GTK apps in GNOME/Cinnamon. Is it possible to have this for Qt and GTK apps in Lxqt?

Use case: a laptop with Full HD screen, an external monitor is 4K UHD. Since there's no way to have per-monitor settings without Wayland, the only solution I've found is to change DPI settings depending on the current screen.

**Comment by tsujan** [comment]
> It'd be great to be able to change DPI settings without restarting everything.

It depends on whether Qt supports a runtime update (I don't think it does). If it does, lxqt-qtplugin might be able to support it.

For now, we need a GUI for users not to worry about the names of EVs.

**Comment by renom** [comment]
@tsujan it's not related with changing DPI settings on the fly, but I've found out that there's a solution to have per-monitor scaling only for Qt apps with `QT_SCREEN_SCALE_FACTORS="DP-1=2;eDP-1=1.5"`. AFAIK, GTK doesn't have something similar to this. But since Lxqt is based on Qt, you could add a GUI to adjust this EV.

**Comment by tsujan** [comment]
@renom Thanks for the info.

I think the developer's main problem is finding the best place for these settings; otherwise, they seem easy to add (except for the on-the-fly DPI change).
