### ISSUE TITLE
Touchpad Settings (Request)

### ISSUE THREAD

**Issue by intialonso** [lxqt/lxqt-config#405]
This is more a request than a bug.

In the mouse settings theres no options for touchpads (vertical and horizontal scroll, tap, etc). It will be great if the option could be included in the settings app.

**Comment by hmollercl** [comment]
Could you change the "Single click to activate items" with something like "tap to click" in the ui?

**Comment by tsujan** [comment]
> Could you change the "Single click to activate items" with something like "tap to click" in the ui?

I agree with this. @yan12125, is it acceptable to you? Or there's a case of single-click that's covered by it?

**Comment by agaida** [comment]
Guess it is swapped over from mouse configuration

**Comment by tsujan** [comment]
> Guess it is swapped over from mouse configuration

Most probably. It should be "Tap to click" and it's better to put "Tap to drag" below it.

**Comment by tsujan** [comment]
Oh, "Tap to drag" may need be ""Tap twice to drag". Confusing...

**Comment by yan12125** [comment]
> is it acceptable to you?

Sure! The replacement sounds more intuitive :)

> Oh, "Tap to drag" may need be "Tap twice to drag". Confusing...

I guess I missed "twice" as the underlying libinput attribute is called LIBINPUT_PROP_TAP_DRAG. Feel free to add "twice"!

**Comment by tsujan** [comment]
> I guess I missed "twice"

@yan12125 I'm not even sure if "twice" is correct here. Dragging isn't done by a simple tapping, of course, but it isn't done by double tapping either because, the second time, the finger remains on touchpad.

The easiest way of finding correct terms is launching KDE settings. I'll do that later and make a pedantic PR ;) The important thing is that LXQt touchpad settings work well.

**Comment by tsujan** [comment]
I think this prevents confusion: https://github.com/lxqt/lxqt-config/pull/460

"Tap and drag" is "Tap-and-drag" in KDE.

**Comment by damian101** [comment]
An option to disable the touchpad would be most important for me.

**Comment by tsujan** [comment]
> An option to disable the touchpad...

Oh, it's missing! It would be a nice addition.

**Comment by zerinoid** [comment]
Hello, sorry for the dumb question, but how do I implement this config? I've just installed lubuntu 18.10 and I have no such config entry for touchpad. this is the only place I've seen any reference to a GUI config and yet I'm not able to uncover how do it. thank you in advance

**Comment by Chiitoo** [comment]
> Hello, sorry for the dumb question, but how do I implement this config? I've just installed lubuntu 18.10 and I have no such config entry for touchpad. this is the only place I've seen any reference to a GUI config and yet I'm not able to uncover how do it. thank you in advance

What version of LXQt do you have?

I found some pictures of Lubuntu 18.10 having version 0.13.0 of PCManFM-Qt, which would mean that indeed, you'd not have the touchpad settings yet (I believe 0.14.0 would be the earliest release with it).

**Comment by agaida** [comment]
LTS means in this case that you will get the same answer longterm - it is not implemented in 0.13

**Comment by wxl** [comment]
@agaida Sounds a lot like "stable" which doesn't even have 0.12 :rofl:

@zerinoid 18.10 is not an LTS and actually stopped being support in April. Upgrade to 19.04 and problem solved.

**Comment by zerinoid** [comment]
> > Hello, sorry for the dumb question, but how do I implement this config? I've just installed lubuntu 18.10 and I have no such config entry for touchpad. this is the only place I've seen any reference to a GUI config and yet I'm not able to uncover how do it. thank you in advance
> 
> What version of LXQt do you have?
> 
> I found some pictures of Lubuntu 18.10 having version 0.13.0 of PCManFM-Qt, which would mean that indeed, you'd not have the touchpad settings yet (I believe 0.14.0 would be the earliest release with it).

I see. Indeed, my LXQt version is 0.13.0

**Comment by zerinoid** [comment]
> @agaida Sounds a lot like "stable" which doesn't even have 0.12 rofl
> 
> @zerinoid 18.10 is not an LTS and actually stopped being supported in April. Upgrade to 19.04 and problem solved, at least for the basic touchpad configuration. Assuming that this finally gets implemented and released before approximately August 22nd, it will be in 19.10.

Ah, ok. I'm starting to get what LTS means lol. thank you

**Comment by agaida** [comment]
@wxl - let me cite Jack Cohen:
> There is this special biologist word we use for “stable”. It is “dead”.

**Comment by wxl** [comment]
This is a bit of an aside but is there any way we could get more generic configuration options? I know that at least in `xorg.conf`, you can use `InputClass" to match a variety of devices rather than just one. Is there any way we could come up with a solution to do something similar?

**Comment by tsujan** [comment]
I don't have enough knowledge on this but, IMO, "more generic" could mean "poorer". Each device has its own settings, which are most probably different from those of other devices.

**Comment by yan12125** [comment]
It's possible to implement something to apply settings to all devices identified as ID_INPUT_TOUCHPAD or ID_INPUT_MOUSE. Those keywords can be found in https://github.com/lxqt/lxqt-config/pull/109.

**Comment by wxl** [comment]
To be clear, I think that we would have very device-specific settings is great. You'll find nearly every device has its own little quirks that others don't. That said, there are also some similarities that apply to all devices. For example, it would be nice to set natural scrolling universally, so that if one switches devices, one isn't surprised by the behavior.

**Comment by sebasarena** [comment]
> An option to disable the touchpad would be most important for me.

I completely agree with you. 

The only thing that it makes me stay on MATE desktop instead of using LXQt environment, is that MATE has the option to disable the touchpad permanently: https://i.imgur.com/fG5hNll.png

**Comment by sebasarena** [comment]
Hope that you could implement the option to disable the touchpad permanently, inspired by the code of MATE desktop: https://github.com/mate-desktop/mate-control-center/blob/master/capplets/mouse/mate-mouse-properties.c

**Comment by tsujan** [comment]
@yan12125
Would you please add an option to disable a device (touchpad or not)? Does it need a lot of code? I'm not familiar with this part of lxqt-config and so, I prefer not to touch your code.

I disable my touchpad in a startup script and have assigned 2 keyboard shortcuts for enabling and disabling it.

@sebasarena 
Until it's implemented in the GUI, you can find your touchpad ID with `xinput list` and disable it with `xinput set-prop ID "Device Enabled" 0`. Enabling is done by using `1` instead of `0`.

**Comment by yan12125** [comment]
Here you go~ https://github.com/lxqt/lxqt-config/pull/621

I should refactor the code for less copy/paste for a new option if I find time :/

**Comment by tsujan** [comment]
Very good -- and fast. Thanks you!

**Comment by yan12125** [comment]
In #621, we are discussing about disabling the touchpad only when a mouse is plugged. However, how the Linux kernel handles devices is less than ideal. For wireless mouse that are connected via a USB receiver, the kernel lists them even when they are out of the wireless range. Not sure if everyone plugs the receiver away when bringing their laptop out.

**Comment by tsujan** [comment]
> For wireless mouse that are connected via a USB receiver, the kernel lists them even when they are out of the wireless range.

IMHO, we can ignore that scenario when disabling touchpad with a plugged-in mouse. The mouse can also be broken or, for another reason, it may not work properly; these aren't our problem to solve. Having a mouse that's *reported to be plugged-in* can be the sufficient condition for disabling touchpad.

**Comment by damian101** [comment]
@yan12125 I don't think there's anything the Linux kernel could handle differently in this case, for the operating system wireless USB mouse receivers behave identical to wired USB mice.

**Comment by GenNomro** [comment]
Ok I've solved a way to enable tap to click and side of pad scrolling...

Open terminal of choice since were talking Lxqt lets say qterminal

type: xinput list

I get this:

⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=10   [slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                     id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Sleep Button                              id=8    [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=9    [slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                    id=12   [slave  keyboard (3)]

Next in terminal type: xinput enable 10

Test tap to click and pad side scrolling - mine works

Now lets make it load on startup

On the mail panel menu:

Preferences >> LXQt Settings >> Session Settings

Window will open: on left click Autostart

Next on right click: Add

Give it whatever name you like

In "Command" type: xinput enable 10

I set mine to wait for system tray, no reason just did

Click: Ok

On the list find the name you gave it and make sure it is checked in the box

Done

Enjoy

**Comment by tsujan** [comment]
Touchpad settings were added in 2018. Closing...

An option for disabling touchpad is still lacking — it seems that @yan12125 hasn't had time to complete https://github.com/lxqt/lxqt-config/pull/621 — but that's another issue.
